const body = document.querySelector('body');
const toggle = document.getElementById('toggle');
const navigation = document.getElementById('navigation');
const header = document.getElementById('hero');
const section = document.querySelectorAll('#section');
const footer = document.getElementById('footer');
const topButton = document.getElementById('topButton');
toggle.onclick = function () {
    toggle.classList.toggle('active');
    body.classList.toggle('active');
    navigation.classList.toggle('active');
    header.classList.toggle('active');
    section[0].classList.toggle('active');
    section[1].classList.toggle('active');
    section[2].classList.toggle('active');
    section[3].classList.toggle('active');
    section[4].classList.toggle('active');
    section[5].classList.toggle('active');
    section[6].classList.toggle('active');
    section[7].classList.toggle('active');
    section[8].classList.toggle('active');
    section[9].classList.toggle('active');
    section[10].classList.toggle('active');
    section[11].classList.toggle('active');
    section[12].classList.toggle('active');
    section[13].classList.toggle('active');
    footer.classList.toggle('active');
    topButton.classList.toggle('active');
};
